title: Not Your Employer's Data Blog
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: A collection of projects and tutorials
